name = "Custom Modpack"
author = "tekitou"
version = "1.0.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3c4742c364b97d528ef0917de3612fe34463fd075ba5ec274d4d7aba7a9b1a29"

[versions]
forge = "47.4.0"
minecraft = "1.20.1"
